"""The customer communication channel. It writes to a file, never to a customer.

Recoup's dataset is synthetic and its customers are generated by Faker, but the
email addresses and phone numbers that generator produces are structurally valid
and some of them belong to somebody. So there is exactly one messaging path in
this codebase and it terminates in `data/outbox.jsonl` - no SMTP, no SMS
provider, and Razorpay's own link notifications are switched off at the point of
creation (see execute/razorpay_client.create_payment_link).

What is *not* simulated is the cost. Every message carries the real per-unit
price of its channel, those numbers are written to ActionRun.channel_cost_paise,
and the eval subtracts them from gross recovery. A recovery programme that sends
40,000 messages to recover Rs 3L has not recovered Rs 3L, and the only way that
shows up in the report is if the channel costs are carried from the start.

Copy is composed per Strategy, not from one template with the reason spliced in.
A bank-outage notice and an abandoned-cart nudge are different messages with
different jobs: the first tells a customer that nothing is wrong and asks them to
do nothing, the second asks them to come back and pay. Templating them together
produces the tonally deaf "we noticed your payment failed, here's 10% off!" that
recovery tooling is known for.
"""

from __future__ import annotations

import json
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

from recoup.config import PROJECT_ROOT
from recoup.db import ActionType, Customer, RevenueEvent
from recoup.taxonomy import Strategy, profile_for

OUTBOX_PATH = PROJECT_ROOT / "data" / "outbox.jsonl"
"""Append-only JSONL. One line per message, readable by the dashboard and by a
human with `tail -f` - which is the whole point of choosing it over a table."""

MERCHANT_NAME = "Recoup Demo Store"
"""Sender identity. In a real deployment this comes from the merchant's Razorpay
account profile; here it is a constant so the copy reads like a shop rather than
like a system."""

CHANNEL_COST_PAISE = {
    "email": 10,
    "sms": 25,
}
"""Indian transactional rates, rounded to whole paise: roughly Rs 0.10 per
transactional email on a bulk ESP and Rs 0.25 per SMS route including the DLT
levy. Both are small enough to look like zero and neither is - at 40,000 events
they are the difference between a positive and a negative net recovery line."""


@dataclass(frozen=True)
class Message:
    """One outbound message, exactly as it was written to the outbox."""

    message_id: str
    sent_at: str
    event_id: str
    customer_id: str
    to: str
    channel: str
    subject: str
    body: str
    action_type: str
    reason_code: str
    strategy: str
    cost_paise: int
    link_url: str | None = None
    incentive_paise: int = 0
    extra: dict[str, Any] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Formatting
# ---------------------------------------------------------------------------


def rupees(paise: int) -> str:
    """Indian digit grouping: 1,29,900 - not 129,900.

    Customer-facing copy is the one place the Western grouping in the policy
    engine's log strings would be wrong. An SMS from an Indian merchant that
    reads "Rs 129,900" was written by somebody who has never received one.
    """
    whole, fraction = divmod(abs(paise), 100)
    digits = str(whole)

    if len(digits) > 3:
        head, tail = digits[:-3], digits[-3:]
        groups = []
        while len(head) > 2:
            groups.insert(0, head[-2:])
            head = head[:-2]
        if head:
            groups.insert(0, head)
        digits = ",".join([*groups, tail])

    sign = "-" if paise < 0 else ""
    return f"{sign}{digits}" if fraction == 0 else f"{sign}{digits}.{fraction:02d}"


def _first_name(customer: Customer) -> str:
    return customer.name.split()[0] if customer.name.strip() else "there"


# ---------------------------------------------------------------------------
# Copy
# ---------------------------------------------------------------------------


def compose(
    event: RevenueEvent,
    customer: Customer,
    action_type: ActionType,
    link_url: str | None = None,
    incentive_paise: int = 0,
) -> tuple[str, str, str]:
    """Build (channel, subject, body) for one event.

    The channel is chosen with the copy rather than configured separately,
    because it is part of the message. A payment link has to be opened on the
    phone that holds the customer's UPI app, so it goes by SMS; a receivables
    reminder needs to reach a finance inbox where it can be forwarded, so it
    goes by email. Sending each of those over the other channel is how a
    correctly-chosen action still fails to recover anything.
    """
    profile = profile_for(event.reason_code)
    name = _first_name(customer)
    amount = rupees(event.amount_paise)

    # Receivables are collected, not converted - the question is when, not
    # whether. Handled ahead of Strategy because a B2B invoice chase shares
    # PERSUADE with an abandoned cart and should sound nothing like one.
    if event.reason_code == "invoice_overdue":
        pay_line = f"Settle by UPI, netbanking or NEFT here: {link_url}" if link_url else (
            "Reply to this mail and we will send a payment link."
        )
        return (
            "email",
            f"Invoice for Rs {amount} is now overdue",
            f"Hi {name},\n\n"
            f"Our invoice for Rs {amount} is past its due date and still showing as "
            f"open on our side.\n\n"
            f"{pay_line}\n\n"
            f"If it has already been paid, send us the UTR and we will close it off "
            f"at our end.\n\n"
            f"- Accounts, {MERCHANT_NAME}",
        )

    if action_type is ActionType.NUDGE_WITH_INCENTIVE and incentive_paise > 0:
        discount = rupees(incentive_paise)
        net = rupees(event.amount_paise - incentive_paise)
        return (
            "email",
            f"Rs {discount} off the order you left behind",
            f"Hi {name},\n\n"
            f"Your Rs {amount} order at {MERCHANT_NAME} is still saved. Here is "
            f"Rs {discount} off it - you pay Rs {net}.\n\n"
            f"{link_url}\n\n"
            f"UPI, card or netbanking. The price holds for 48 hours.\n\n"
            f"- {MERCHANT_NAME}",
        )

    if profile.strategy is Strategy.RETRY_DELAYED:
        # A notice, not a nudge. There is nothing for the customer to do and
        # asking them to do something anyway invites a second, duplicate payment.
        # A link is offered only as an opt-out of the wait, never as the ask.
        cta = f" If you would rather not wait, pay now: {link_url}" if link_url else ""
        return (
            "sms",
            f"Rs {amount} payment - bank issue, no action needed",
            f"Hi {name}, your Rs {amount} payment to {MERCHANT_NAME} could not be "
            f"completed because your bank was briefly unreachable. Nothing has been "
            f"charged and your order is held. We will put it through again shortly - "
            f"no action needed from you.{cta}",
        )

    if profile.strategy is Strategy.RETRY_NOW:
        cta = f" Try again: {link_url}" if link_url else " Please try again from your cart."
        return (
            "sms",
            f"Rs {amount} payment did not go through",
            f"Hi {name}, the {profile.label.lower()} stopped your Rs {amount} payment "
            f"to {MERCHANT_NAME}. Nothing was charged and your order is still "
            f"reserved.{cta}",
        )

    if profile.strategy is Strategy.RETRY_ON_LIQUIDITY:
        cta = f" Or pay now by UPI: {link_url}" if link_url else ""
        return (
            "sms",
            f"Rs {amount} payment - we will try once more",
            f"Hi {name}, your bank declined the Rs {amount} payment to "
            f"{MERCHANT_NAME}. Your order is held, nothing has been charged, and we "
            f"will present it once more at the start of next month.{cta}",
        )

    if profile.strategy is Strategy.SWITCH_RAIL:
        alternatives = " or ".join(r.value for r in profile.switch_to) or "UPI"
        return (
            "sms",
            f"Pay Rs {amount} by {alternatives} instead",
            f"Hi {name}, your {event.rail} could not be used for the Rs {amount} "
            f"payment to {MERCHANT_NAME} ({profile.label.lower()}). Pay by "
            f"{alternatives} here instead - takes about 30 seconds: {link_url}",
        )

    # PERSUADE without money attached: the customer chose not to pay, so the only
    # honest lever is reminding them the order still exists.
    cta = f"\n\n{link_url}" if link_url else "\n\nIt is waiting in your cart."
    return (
        "email",
        f"Your Rs {amount} order at {MERCHANT_NAME} is still saved",
        f"Hi {name},\n\n"
        f"You left a Rs {amount} order with us and did not finish paying for it. "
        f"We have held it aside.{cta}\n\n"
        f"UPI, card and netbanking all work. If you have changed your mind that is "
        f"completely fine - this is the only reminder we will send.\n\n"
        f"- {MERCHANT_NAME}",
    )


# ---------------------------------------------------------------------------
# Sending
# ---------------------------------------------------------------------------


def send(
    event: RevenueEvent,
    customer: Customer,
    action_type: ActionType,
    now: datetime,
    link_url: str | None = None,
    incentive_paise: int = 0,
    path: Path | None = None,
) -> Message:
    """Compose one message and append it to the outbox. Returns what was written.

    The caller is responsible for the ContactLog row: the fatigue cap is a policy
    concern and this module deliberately knows nothing about policy. What it does
    guarantee is that a Message came back with a real `cost_paise` on it.
    """
    profile = profile_for(event.reason_code)
    channel, subject, body = compose(
        event, customer, action_type, link_url, incentive_paise
    )

    message = Message(
        message_id=f"msg_{event.id}_{int(now.timestamp())}_{channel}",
        sent_at=now.isoformat(timespec="seconds"),
        event_id=event.id,
        customer_id=customer.id,
        to=customer.contact if channel == "sms" else customer.email,
        channel=channel,
        subject=subject,
        body=body,
        action_type=action_type.value,
        reason_code=event.reason_code,
        strategy=profile.strategy.value,
        cost_paise=CHANNEL_COST_PAISE[channel],
        link_url=link_url,
        incentive_paise=incentive_paise,
    )

    target = path or OUTBOX_PATH
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("a", encoding="utf-8") as fh:
        fh.write(json.dumps(asdict(message), ensure_ascii=False) + "\n")

    return message


def read_all(path: Path | None = None) -> list[dict[str, Any]]:
    """Every message ever sent. Used by the dashboard and by the tests."""
    target = path or OUTBOX_PATH
    if not target.exists():
        return []
    with target.open("r", encoding="utf-8") as fh:
        return [json.loads(line) for line in fh if line.strip()]
